In [ ]:
from gensim.models import KeyedVectors

# 读取词向量文件
path = 'output\quantangshi_emb.txt'
emb = KeyedVectors.load_word2vec_format(path, binary=False, unicode_errors='ignore')
print(emb)

In [5]:
# import numpy as np
# from gensim.models import KeyedVectors
## 生成鄰接矩陣
# # Load word vectors
# path ='output\quantangshi_emb.txt'
# emb = KeyedVectors.load_word2vec_format(path, binary=False, unicode_errors='ignore')

# # Get the list of words
# words = emb.index_to_key

# # Calculate similarity (using cosine similarity as an example)
# def cosine_similarity(word1, word2):
#     vec1 = emb.get_vector(word1)
#     vec2 = emb.get_vector(word2)
#     dot_product = np.dot(vec1, vec2)
#     norm1 = np.linalg.norm(vec1)
#     norm2 = np.linalg.norm(vec2)
#     similarity = dot_product / (norm1 * norm2)
#     return similarity

# # Build the adjacency matrix
# num_words = len(words)
# adj_matrix = np.zeros((num_words, num_words))
# for i in range(num_words):
#     for j in range(i+1, num_words):
#         word1 = words[i]
#         word2 = words[j]
#         similarity = cosine_similarity(word1, word2)
#         adj_matrix[i][j] = similarity
#         adj_matrix[j][i] = similarity

# print(adj_matrix)


[[0.         0.87850261 0.53385812 ... 0.27132159 0.35483015 0.31306884]
 [0.87850261 0.         0.48245493 ... 0.21311283 0.2970328  0.2724368 ]
 [0.53385812 0.48245493 0.         ... 0.30841663 0.03915691 0.20762514]
 ...
 [0.27132159 0.21311283 0.30841663 ... 0.         0.30434901 0.27039421]
 [0.35483015 0.2970328  0.03915691 ... 0.30434901 0.         0.16695002]
 [0.31306884 0.2724368  0.20762514 ... 0.27039421 0.16695002 0.        ]]


In [7]:
import numpy as np

# 将adj_matrix保存为本地文件
np.save('output/adj_matrix.npy', adj_matrix)

In [8]:
# 从本地文件加载adj_matrix
loaded_adj_matrix = np.load('output/adj_matrix.npy')

In [9]:
import networkx as nx
from infomap import Infomap

# 假设你有词向量表示和词汇图的邻接矩阵adj_matrix
# 例如，adj_matrix[i][j]表示词汇i和j之间的相似度或权重

# 构建无向图
G = nx.Graph()
for i in range(len(adj_matrix)):
    for j in range(i+1, len(adj_matrix)):
        weight = adj_matrix[i][j]
        if weight > 0:  # 只添加相似度大于0的边
            G.add_edge(i, j, weight=weight)

# 初始化Infomap算法
infomap = Infomap()

# 添加边到Infomap算法
for edge in G.edges():
    infomap.addLink(*edge)

# 运行Infomap算法进行聚类
infomap.run()

# 获取聚类结果
cluster_result = {}
for node, cluster_id in infomap.iterTree():
    if cluster_id not in cluster_result:
        cluster_result[cluster_id] = []
    cluster_result[cluster_id].append(node)

# 输出聚类结果
for cluster_id, words in cluster_result.items():
    print(f"Cluster {cluster_id}:")
    for word_idx in words:
        print(f"  Word {word_idx}: {word_list[word_idx]}")  # 假设有一个word_list，保存着词汇列表


ModuleNotFoundError: No module named 'infomap'